
```{r setup-appndx-B, echo=FALSE, include=FALSE}
  ###   set a global knitr options
  knitr::opts_chunk$set(
    cache = FALSE,
    message = FALSE,
    dev = "svg",
    fig.topcaption = TRUE,
    fig.cap = TRUE)

  knitr::knit_hooks$set(class = function(before, options, envir) {
    if(before){
      sprintf("<div class = '%s'>", options$class)
    }else{
      "</div>"
    }
  })

  fig.out.ex <- 'data-prefix="Figure"'
  tab.out.ex <- 'style="display: none;" data-prefix="Table"'

  ###   Load some R packages and functions required for HTML table creation silently.
  ###   Load SGP and other packages here to avoid messages.
  require(ymlthis)
	require(data.table)
  require(SGP)

  ###   Set Table, Figure and Equation Counters
  # startAppendix()
  setCounters()
  options(table_counter=FALSE)
  options(table_num_str = "B%d") # Prepend Appendix Letter when using tblNum()
  options(table_counter_str = paste0("**Table ", "B", "%s:**")) # "**Table A%s:**" LETTERS[appendix.number]
  options(fig_num_str = "B%d") # Prepend Appendix Letter when using figNum()
  options(fig_caption_no_sprintf = paste0("**Figure ", "B", "%d:** %s")) # "**Figure A%d:** %s"

  ###   Utility function - Assumes first two "levels" are the main dichotomy
  ord <- function(x) { # <sup>th</sup>
    o <- toOrdinal::toOrdinal(x)
    return(paste0(x, "<sup>", substr(o, nchar(o)-1, nchar(o)),"</sup>"))
  }

  "%w/o%" <- function(x,y) x[!x %in% y]

```

```{css, echo=FALSE}
.figure img {
    max-width: 45%;
}
```

<!--  create _bookdown.yml file for labeling `Figures` and `Tables` with appendix prefix.-->

```{r, include=FALSE}
	ymlthis::yml_empty() %>%
		ymlthis::yml_bookdown_opts(
			language=list(label=list(fig="'Figure B'", tab="'Table B'"))
		) %>%
			Literasee:::writeYAML(filename = '_bookdown.yml', fences=FALSE)
```
